# Generated by Django 3.1.3 on 2022-06-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220630_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='flag',
        ),
    ]
